name = "glow_auth"
version = "0.5.0"

licences = ["Apache-2.0"]
description = "OAuth2 helpers in Gleam..."
repository = { type = "github", user = "adz", repo = "glow_auth" }
links = [{ title = "Website", href = "https://github.com/adz/glow_auth" }]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_erlang = "~> 0.24"
gleam_http = "~> 3.5"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
