name = "glow_auth"
version = "1.0.0"

licences = ["Apache-2.0"]
description = "OAuth2 helpers in Gleam..."
repository = { type = "github", user = "adz", repo = "glow_auth" }
links = [{ title = "Website", href = "https://github.com/adz/glow_auth" }]
gleam = ">= 1.11.1"

[dependencies]
gleam_stdlib = "~> 0.60"
gleam_http = "~> 4.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_time = ">= 1.0.0-rc2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
